### ISSUE TITLE
React.DOM.thread is not a function

### ISSUE THREAD

**Issue by git-clay** [pereiradaniel/LiftProgressTutorial#1]
In the `app>assets>javascripts>components>lifts.js.coffee` I ran into the error "React.DOM.thread is not a function" which would not allow the table to be displayed.

The fix was to just remove that line completely.

Great tutorial!

**Comment by markhern** [comment]
Which branch? I'm not seeing React.DOM.thread in the code or video. It should remove the 'r' so that its 'thead' instead. That's the fix.

**Comment by git-clay** [comment]
My mistake. That is definitely it. Dumb typo on my end. Great tutorial, really helped me a lot

**Comment by git-clay** [comment]
My mistake. That is definitely it. Dumb typo on my end. Great tutorial, really helped me a lot

**Comment by pereiradaniel** [comment]
Thanks for using the tutorial!
